DROP DATABASE IF EXISTS fenty;
CREATE DATABASE fenty;
USE fenty;

CREATE TABLE products(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  price VARCHAR(255) NOT NULL,
  rating_star FLOAT(1) NOT NULL,
  rating_num INT NOT NULL,
  fav BOOLEAN NOT NULL,
  more_shades BOOLEAN NOT NULL,
  category VARCHAR(255) NOT NULL,
  foreground VARCHAR(255) NOT NULL,
  background VARCHAR(255) NOT NULL
);

CREATE TABLE instagram (
  id INT AUTO_INCREMENT PRIMARY KEY,
  picture_url VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  product_used1 VARCHAR(255) NOT NULL,
  product_used2 VARCHAR(255),
  product_used3 VARCHAR(255)
);

INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FACE & BODY KABUKI BRUSH 120', '', '$34.00', 4.6, 30, TRUE, FALSE, 'TOOLS', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/1a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/1b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('DIAMOND BOMB ALL-OVER DIAMOND VEIL', 'How Many Carats?!', '$39.00', 4.3, 240, TRUE, TRUE, 'BODY MAKEUP',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/2a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/2b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('KILLAWATT FREESTYLE HIGHLIGHTER', 'Mean Money/ Hu$tla Baby', '$36.00', 4.9, 1046, TRUE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/3a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/3b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Fenty Glow', '$19.00', 4.8, 1948, TRUE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/4a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/4b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR SOFT MATTE LONGEWEAR FOUNDATION #340', '', '$35.00', 4.7, 4006, TRUE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/5a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/5b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('KABUKI-BUFF FOUNDATION BRUSH 115', '', '$36.00', 4.8, 11, FALSE, FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/6a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/6b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR SETTING POWDER', 'Honey', '$32.00', 4.6, 91, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/7a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/7b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRECISION MAKEUP SPONGE 100', '', '$16.00', 4.2, 43, TRUE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/8a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/8b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR INSTANT RETOUCH PRIMER', '', '$32.00', 4.6, 254,TRUE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/9a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/9b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR INSTANT RETOUCH CONCEALER #340', '', '$26.00', 4.5, 138, TRUE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/10a.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/10b.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('HYDRATING COMPLEXION ESSENTIALS WITH BRUSH', '', '$81.00', 5, 123, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/11A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/11B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('CHEEKS OUT FREESTYLE CREAM BRONZER', 'Amber', '$32.00', 4.9, 2, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/12A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/12B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATCH STIX SHIMMER SKINSTICK', 'Starstruck', '$25.00', 4.8, 238, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/13A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/13B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('KILLAWATT FOIL FREESTYLE HIGHLIGHTER', 'Mimosa Sunrise/Sangria Sunset', '$36.00', 5,155, TRUE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/14A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/14B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SUN STALKR INSTANT WARMTH BRONZER', 'Caramel Cutie', '$30.00', 4.5, 46, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/15A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/15B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR HYDRATING LONGWEAR FOUNDATION #340', '', '$32.00', 4, 63, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/16A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/16B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PORTABLE HIGHLIGHTER BRUSH 140', '', '$24.00', 5, 4, FALSE,FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/17A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/17B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATCH STIX TRIO', 'Medium 200', '$54 ($75 value)', 4.6, 369, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/18A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/18B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('KILLAWATT FREESTYLE HIGHLIGHTER', 'Trophy Wife', '$36.00', 4.8, 1046, TRUE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/19A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/19B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('CHEEK-HUGGING HIGHLIGHT BRUSH 120', '', '$32.00', 4.5, 38, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/20A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/20B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR MINI INSTANT RETOUCH SETTING POWDER', 'Cashew', '$18.00', 4.9, 7, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/21A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/21B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FAIRY BOMB SHIMMER POWDER', 'Rose On Ice', '$28.00', 4.9, 50, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/22A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/22B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BODY LAVA BODY LUMINIZER', 'Brown Sugar', '$59.00', 4.5, 534, TRUE,TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/23A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/23B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('CHEEKS OUT FREESTYLE CREAM BLUSH', 'Petal Poppin', '$20.00', 4.4, 12, FALSE, TRUE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/24A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/24B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR MINI INSTANT RETOUCH PRIMER', 'Soft Matte', '$16.00', 4, 6, FALSE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/25A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/25B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('ALL-OVER EYESHADOW BRUSH 200', '', '$24.00', 4.9, 3, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/26A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/26B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FLYLINER LONGWEAR LIQUID EYELINER', 'Cuz Im Black', '$22.00', 4, 289, TRUE, FALSE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/27A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/27B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA LIP PAINT LONGWEAR FLUID LIP COLOR', 'Uncuffed', '$25.00', 4.5, 1505, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/28A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/28B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('CHEEK-HUGGING BRONZER BRUSH 190', '', '$36.00', 4.2, 8, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/29A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/29B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA LIP PAINT LONGWEAR FLUID LIP COLOR', 'Uncensored', '$25.00', 4.5, 1505, TRUE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/30A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/30B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('LIQUID DIAMOND BOMB GLITTER HIGHLIGHTER', 'Rollin Dice', '$28.00', 3.8, 15, FALSE,FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/31A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/31B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Diamond Milk', '$19.00', 4.8, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/32A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/32B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO KISSR DUO', '', '$29 ($34 value)', 4.2, 54, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/33A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/33B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MOROCCAN SPICE EYESHADOW PALETTE', '', '$29.00', 5, 234, TRUE, FALSE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/34A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/34B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('TWO LIL MATTEMOISELLES PLUSH MATTE LIPSTICK DUO', '', '$19.00', 4.5, 29, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/35A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/35B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('LIL MATCH STIX DUO MINI SHIMMER SKINSTICK SET', '', '$22.00', 4.9, 25, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/36A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/36B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FLY BABY MINI EYE PRIMER AND LINER SET', '', '$24.00', 4.3,13, FALSE, FALSE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/37A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/37B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('DIAMOND BOMB BABY MINI FACE AND LIP SET', '', '$25.00', 4.1, 5, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/38A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/38B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('INVISIMATTE COMPLETE ESSENTIALS', '', '$54 ($72 value)', 4.6, 29, FALSE, FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/39A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/39B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PORTABLE TOUCH BRUSH', '', '$24.00', 4, 19, FALSE,FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/40A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/40B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('INVISIMATTE BLOTTING PAPER', '', '$16.00', 4, 18, TRUE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/41A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/41B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('INVISIMATTE BLOTTING PAPER REFILL', '', '$10.00', 5, 3, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/42A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/42B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('WHAT IT DEW MAKEUP REFRESHING SPRAY', '', '$30.00', 3.8, 9, FALSE, FALSE, 'BODY MAKEUP',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/43A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/43B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('HYDRATING + SOFT MATTE COMPLEXION ESSENTIALS WITH BRUSH', '', '$81 ($103 value)', 4.5, 412, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/44A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/44B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('POWDER PUFF SETTING BRUSH 170', '', '$34.00', 5, 12, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/45A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/45B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR AMPLIFYING EYE PRIMER', '', '$22.00', 4.7, 36, FALSE, FALSE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/46A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/46B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('CLF MAKEUP CASE CARRY-ALL MAKEUP ORGANIZER', '', '$45.00', 5, 33, FALSE, FALSE, 'TOOLS',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/47A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/47B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('COMPLETE YOUR COMPLEXION ESSENTIALS', '', '$68 ($88 value)', 4.6, 132, FALSE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/48A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/48B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR SETTING POWDER ESSENTIALS CUSTOM 2-PC SET', '', '$66.00', 4.4, 1322, FALSE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/49A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/49B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB: DOUBLE TAKE LIP DUO', '', '$29 ($38 value)', 5, 3, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/50A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/50B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Hot Chocolit', '$19.00', 4.9, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/51A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/51B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Glass Slipper', '$19.00', 4.9, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/52A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/52B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', '$weet Mouth', '$19.00', 4.9, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/53A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/53B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Fu$$y', '$19.00', 4.9, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/54A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/54B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('GLOSS BOMB UNIVERSAL LIP LUMINIZER', 'Diamond Milk', '$19.00', 4.9, 1948, FALSE, TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/55A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/55B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BOMB BABY MINI LIP AND FACE SET', '', '$23.00', 4.9, 253, TRUE, FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/56A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/56B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA BOSS BOLDS LONGWEAR FLUID LIP COLOR TRIO', '', '$50 ($75 value)', 4.5, 14, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/57A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/57B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA BOSS NUDES LONGWEAR FLUID LIP COLOR TRIO', '', '$50', 4.9, 16,FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/58A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/58B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATTEMOISELLE PLUSH MATTE LIPSTICK', 'Dragon Mami', '$18.00', 4.6, 643, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/59A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/59B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATTEMOISELLE PLUSH MATTE LIPSTICK', 'Clapback', '$18.00', 4.6, 643, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/60A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/60B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATTEMOISELLE PLUSH MATTE LIPSTICK', 'Ballerina Blackout', '$18.00', 4.6, 643, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/61A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/61B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATTEMOISELLE PLUSH MATTE LIPSTICK', 'MaDamn', '$18.00', 4.6, 643, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/62A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/62B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('MATTEMOISELLE PLUSH MATTE LIPSTICK', 'Shawty', '$18.00', 4.6, 643, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/63A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/63B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA NEW YEAR HIGHLIGHTER + LIP SET: LUNAR NEW YEAR EDITION', '', '$50 ($61 value)', 5, 1, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/64A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/64B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('POUTSICLE JUICY SATIN LIPSTICK', 'Alpha Doll', '$14.00', 4.8, 45, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/65A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/65B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STARLIT HYPER-GLITZ LIPSTICK', 'Gravity', '$9.00', 4.7, 138, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/66A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/66B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STARLIT HYPER-GLITZ LIPSTICK', 'Sci-Fly', '$9.00', 4.7, 138, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/67A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/67B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STARLIT HYPER-GLITZ LIPSTICK', '$upanova', '$9.00', 4.7, 138, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/68A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/68B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('STUNNA LIP PAINT LONGWEAR FLUID LIP COLOR', 'Uninvited', '$25.00', 4.5, 1505, FALSE,TRUE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/69A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/69B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO KISSR LIP-LOVING SCRUBSTICK', '', '$16.00', 4.8, 18, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/70A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/70B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO KISSR LUSCIOUS LIP BALM', '', '$18.00', 4.7, 51, FALSE,FALSE, 'LIP PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/71A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/71B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FULL FRONTAL VOLUME LIFT & CURL MASCARA', 'Cuz Im Black', '$24.00', 4.5, 39, FALSE,FALSE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/72A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/72B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '1 - True Neutrals', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/73A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/73B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '2 - Cool Neutrals', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/74A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/74B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '3 - Deep Neutrals', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/75A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/75B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '4 - Rose', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/76A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/76B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '5 - Peach', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/77A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/77B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '6 - Smoky', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/78A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/78B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '7 - Cadet', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/79A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/79B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('SNAP SHADOWS MIX & MATCH EYESHADOW PALETTE', '8 - Pastel Frost', '$25.00', 4.8, 28, FALSE, TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/80A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/80B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Light Blonde', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/81A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/81B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Soft Red', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/82A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/82B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Dark Auburn', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/83A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/83B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Ash Brown', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/84A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/84B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Light Brown', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/85A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/85B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Dark Brown', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/86A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/86B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Black-Brown', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/87A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/87B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Soft Black', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/88A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/88B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BROW MVP ULTRA FINE BROW PENCIL & STYLER', 'Deep Black', '$20.00', 3.7, 96, FALSE,TRUE, 'EYE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/89A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/89B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('DIAMOND BOMB ALL-OVER DIAMOND VEIL', 'Cognac Candy', '$39.00', 4.8, 240, FALSE,TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/90A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/90B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BODY LAVA BODY LUMINIZER', 'Who Needs Clothes?!', '$59.00', 4.9, 534, FALSE, TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/91A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/91B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BODY LAVA BODY LUMINIZER', 'Cognac Candy', '$59.00', 4.9, 534, FALSE, TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/92A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/92B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('BABY BUKI BRUSH 165', '', '$20.00', 3, 4, FALSE,FALSE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/93A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/93B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FACE & BODY KABUKI BRUSH 160', '', '$34.00', 4.9, 30, FALSE,FALSE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/94A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/94B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('DIAMOND BOMB BUKI DUO ALL-OVER DIAMOND VEIL + BRUSH', '', '$73.00', 4.2, 11, FALSE,FALSE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/95A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/95B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FAIRY BOMB SHIMMER POWDER', 'Coppa Chill', '$28.00', 4.9, 50, FALSE,TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/96A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/96B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FAIRY BOMB SHIMMER POWDER', '24Kray', '$28.00', 4.9, 50, FALSE,TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/97A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/97B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('FAIRY BOMB SHIMMER POWDER', 'Trophy Wife', '$28.00', 4.9, 50, FALSE,TRUE, 'BODY PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/98A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/98B.png');
INSERT INTO products (name, description, price, rating_star, rating_num, fav, more_shades, category, foreground, background) VALUES ('PRO FILTR INSTANT RETOUCH PRIMER', '', '$32.00', 4.6, 254, TRUE, FALSE, 'FACE PRODUCT',  'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/99A.png', 'https://fenty-db.s3-us-west-1.amazonaws.com/Fenty+SS/99B.png');